# This file contains settings for CLASSIC, used by both source scripts and the executable.

CLASSIC_Settings:

# Set to true if you want CLASSIC to periodically check for its own updates online through GitHub.
  Update Check: true

# Set to true if you want CLASSIC to prioritize scanning the Virtual Reality version of your game.
  VR Mode: false

# FCX - File Check Xtended | Set to true if you want CLASSIC to check the integrity of your game files and core mods.
  FCX Mode: true

# IMI - Ignore Manual Installation | Set to true if you want CLASSIC to hide / ignore most manual installation warnings.
# I still highly recommend that you install all Buffout 4 files and requirements manually, WITHOUT using a mod manager.
  IMI Mode: false

# Set to true if you want CLASSIC to remove some unnecessary lines and redundant information from your crash log files.
# CAUTION: Changes will be permanent for each crash log you scan after. May hide info useful for debugger programs.
  Simplify Logs: false

# Set to true if you want CLASSIC to show extra stats about scanned logs in the command line / terminal window.
# NOTICE: This setting currently has no effect, crash log stats will be fully implemented in a future update. 
  Show Statistics: false

# Set to true if you want CLASSIC to move all unsolved logs and their autoscans to CL-UNSOLVED folder.
# Unsolved logs are all crash logs where CLASSIC didn't detect any known crash errors or messages.
  Move Unsolved Logs: false

# Copy-paste your INI directory path below. Ex. INI Folder Path: INIFiles_Path = C:/Users/Zen/Documents/My Games/Fallout4
# If you are using MO2, I recommend disabling Profile Specific Game INI Files, located in Tools > Profiles
  INI Folder Path:

# Copy-paste your mod directory path below. This can be either your Fallout 4 / Data folder or your
# deployed mods folder (Ex. Mod Organizer 2 / mods | deployed mods folder is required if using MO2).
  MODS Folder Path:

# Copy-paste your custom scan folder path below. Ex. SCAN Custom Path: C:/Users/Zen/Documents/My Games/Fallout4/F4SE
# If no path is set, CLASSIC will search for crash logs in the same folder from which you are running the executable.
  SCAN Custom Path:
